In [ ]:
import pandas as pd
import numpy as np
#load the dataset as a pandas DataFrame
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
# retrieve numpy array
dataset = df.values
# df=df[0:]
# df.drop()
print(df)
print(df.dtypes)



      Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0      41       Yes  ...                       0                     5
1      49        No  ...                       1                     7
2      37       Yes  ...                       0                     0
3      33        No  ...                       3                     0
4      27        No  ...                       2                     2
...   ...       ...  ...                     ...                   ...
1465   36        No  ...                       0                     3
1466   39        No  ...                       1                     7
1467   27        No  ...                       0                     3
1468   49        No  ...                       0                     8
1469   34        No  ...                       1                     2

[1470 rows x 35 columns]
Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate        

In [ ]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()
df.drop(["Department","BusinessTravel","EducationField","JobRole","Over18"],inplace=True,axis=1)
cleanup_nums = {"Gender":     {"Male": 0, "Female": 1},
                "MaritalStatus": {"Single": 0, "Married": 1, "Divorced": 2 },
                "Attrition" : {"Yes" : 1, "No" : 0},
                "OverTime" : {"Yes" : 1, "No" : 0}
                }

In [ ]:
obj_df

Attrition     BusinessTravel  ... Over18 OverTime
0          Yes      Travel_Rarely  ...      Y      Yes
1           No  Travel_Frequently  ...      Y       No
2          Yes      Travel_Rarely  ...      Y      Yes
3           No  Travel_Frequently  ...      Y      Yes
4           No      Travel_Rarely  ...      Y       No
...        ...                ...  ...    ...      ...
1465        No  Travel_Frequently  ...      Y       No
1466        No      Travel_Rarely  ...      Y       No
1467        No      Travel_Rarely  ...      Y      Yes
1468        No  Travel_Frequently  ...      Y       No
1469        No      Travel_Rarely  ...      Y       No

[1470 rows x 9 columns]

In [ ]:
df

Age Attrition  ...  YearsSinceLastPromotion  YearsWithCurrManager
0      41       Yes  ...                        0                     5
1      49        No  ...                        1                     7
2      37       Yes  ...                        0                     0
3      33        No  ...                        3                     0
4      27        No  ...                        2                     2
...   ...       ...  ...                      ...                   ...
1465   36        No  ...                        0                     3
1466   39        No  ...                        1                     7
1467   27        No  ...                        0                     3
1468   49        No  ...                        0                     8
1469   34        No  ...                        1                     2

[1470 rows x 30 columns]

In [ ]:
Y=df["PerformanceRating"]

In [ ]:

new_obj_df = df.replace(cleanup_nums)
new_obj_df.head()

Age  Attrition  ...  YearsSinceLastPromotion  YearsWithCurrManager
0   41          1  ...                        0                     5
1   49          0  ...                        1                     7
2   37          1  ...                        0                     0
3   33          0  ...                        3                     0
4   27          0  ...                        2                     2

[5 rows x 30 columns]

In [ ]:
X=new_obj_df

In [ ]:
new_obj_df.dtypes


Age                         int64
Attrition                   int64
DailyRate                   int64
DistanceFromHome            int64
Education                   int64
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobSatisfaction             int64
MaritalStatus               int64
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
OverTime                    int64
PercentSalaryHike           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# Convert to categorical data by converting data to integers
# X_cat = X.astype(int)

# 10 Features with highest chi-squared statistics are selected
chi2_features = SelectKBest(chi2, k=10)
X_kbest_features = chi2_features.fit_transform(X, Y)

# Reduced Features
print(X.shape[1])
print(X_kbest_features.shape[1])

29
10


In [ ]:
X_kbest_features

array([[   1,    1, 5993, ...,    4,    0,    5],
       [   8,    2, 5130, ...,    7,    1,    7],
       [   2,    4, 2090, ...,    0,    0,    0],
       ...,
       [   4, 2064, 6142, ...,    2,    0,    3],
       [   2, 2065, 5390, ...,    6,    0,    8],
       [   8, 2068, 4404, ...,    3,    1,    2]])

In [ ]:
X

Age  Attrition  ...  YearsSinceLastPromotion  YearsWithCurrManager
0      41          1  ...                        0                     5
1      49          0  ...                        1                     7
2      37          1  ...                        0                     0
3      33          0  ...                        3                     0
4      27          0  ...                        2                     2
...   ...        ...  ...                      ...                   ...
1465   36          0  ...                        0                     3
1466   39          0  ...                        1                     7
1467   27          0  ...                        0                     3
1468   49          0  ...                        0                     8
1469   34          0  ...                        1                     2

[1470 rows x 29 columns]

In [ ]:
X_kbest_features[1][:]

array([    8,     2,  5130, 24907,     1,    23,     4,     7,     1,
           7])

In [ ]:
chi2_features.scores_

array([0.00000000e+00, 0.00000000e+00, 1.75702781e-03, 3.45551526e-03,
       1.02892450e-02, 1.20352227e-02, 1.65183353e-02, 2.01200275e-02,
       2.35163744e-02, 4.34553849e-02, 6.67663172e-02, 9.28392021e-02,
       1.69407848e-01, 2.11704468e-01, 2.30263088e-01, 3.18521396e-01,
       3.58564443e-01, 3.92778420e-01, 5.63029323e-01, 6.22339723e-01,
       6.76182532e-01, 2.23308525e+00, 2.36364244e+00, 5.58113892e+00,
       7.71862580e+00, 2.15322058e+02, 5.00544082e+02, 7.74159318e+02,
       1.46754727e+03])

In [ ]:
X_kbest_features[1][1]

2

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_kbest_features, Y, test_size=0.25,random_state=0)
 


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,Y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[307   0]
 [  0  61]]


1.0